//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuteBot.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuteBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///  &quot;Properties&quot;: [
        ///    {
        ///      &quot;Item&quot;: &quot;None&quot;,
        ///      &quot;Value&quot;: &quot;&quot;
        ///    },
        ///    {
        ///      &quot;Item&quot;: &quot;SoundBoard&quot;,
        ///      &quot;Value&quot;: &quot;False&quot;
        ///    },
        ///    {
        ///      &quot;Item&quot;: &quot;PlayList&quot;,
        ///      &quot;Value&quot;: &quot;False&quot;
        ///    },
        ///    {
        ///      &quot;Item&quot;: &quot;TrackSelection&quot;,
        ///      &quot;Value&quot;: &quot;False&quot;
        ///    },
        ///    {
        ///      &quot;Item&quot;: &quot;OnlineSync&quot;,
        ///      &quot;Value&quot;: &quot;False&quot;
        ///    },
        ///    {
        ///      &quot;Item&quot;: &quot;LiveMidi&quot;,
        ///      &quot;Value&quot;: &quot;False&quot;
        ///    },
        ///    {
        ///      &quot;Item&quot;: &quot;SoundEffects&quot;,
        ///      &quot;Value&quot;: &quot;True&quot;
        ///    },
        ///    {
        ///      &quot;Item&quot;: &quot;Co [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string DefaultConfig {
            get {
                return ResourceManager.GetString("DefaultConfig", resourceCulture);
            }
        }
    }
}
